version: "3.9"

services:
    app:
        container_name: app
        image: api-usuabilidade
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}"